In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
df = pd.read_csv(r"C:\Users\vishwa\Downloads\airline_passenger_satisfaction.csv")

In [3]:
df

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129875,25971,78463,Male,disloyal Customer,34,Business travel,Business,526,3,3,...,4,3,2,4,4,5,4,0,0.0,neutral or dissatisfied
129876,25972,71167,Male,Loyal Customer,23,Business travel,Business,646,4,4,...,4,4,5,5,5,5,4,0,0.0,satisfied
129877,25973,37675,Female,Loyal Customer,17,Personal Travel,Eco,828,2,5,...,2,4,3,4,5,4,2,0,0.0,neutral or dissatisfied
129878,25974,90086,Male,Loyal Customer,14,Business travel,Business,1127,3,3,...,4,3,2,5,4,5,4,0,0.0,satisfied
129879,25975,34799,Female,Loyal Customer,42,Personal Travel,Eco,264,2,5,...,1,1,2,1,1,1,1,0,0.0,neutral or dissatisfied

In [4]:
df.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [5]:
df.shape

(129880, 25)

In [6]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [7]:
df.isnull().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
satisfaction                           0
dtype: int64

In [8]:
df['Arrival Delay in Minutes'].fillna(0)

0         18.0
1          6.0
2          0.0
3          9.0
4          0.0
          ...
129875     0.0
129876     0.0
129877     0.0
129878     0.0
129879     0.0
Name: Arrival Delay in Minutes, Length: 129880, dtype: float64

In [9]:
df.isnull().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
satisfaction                           0
dtype: int64

In [10]:
df['Arrival Delay in Minutes'].fillna(0,inplace = True)

C:\Users\vishwa\AppData\Local\Temp\ipykernel_13324\1392030200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Arrival Delay in Minutes'].fillna(0,inplace = True)

In [11]:
df.isnull().sum()

Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [12]:
for i in df:
    print("*"*10,i,"*"*10)
    print()
    print(df[i].unique())
    print()

********** Unnamed: 0 **********

[     0      1      2 ... 103901 103902 103903]

********** id **********

[ 70172   5047 110028 ...  37675  90086  34799]

********** Gender **********

['Male' 'Female']

********** Customer Type **********

['Loyal Customer' 'disloyal Customer']

********** Age **********

[13 25 26 61 47 52 41 20 24 12 53 33 45 38  9 17 43 58 23 57 49 36 22 31
 15 35 67 37 40 34 39 50 29 54 21 28 27 69 60 48 59 46 30 66 64 44 51 32
 19 42 16 11 62  8 56 68 55 18 65 72 70 63 10  7 14 80 74 71 85 73 76 77
 75 79 78]

********** Type of Travel **********

['Personal Travel' 'Business travel']

********** Class **********

['Eco Plus' 'Business' 'Eco']

********** Flight Distance **********

[ 460  235 1142 ... 1003 1441  884]

********** Inflight wifi service **********

[3 2 4 1 5 0]

********** Departure/Arrival time convenient **********

[4 2 5 3 1 0]

********** Ease of Online booking **********

[3 2 5 4 1 0]

********** Gate location **********

[1 3 2 5 4 0]

********** Food and drink **********

[5 1 2 4 3 0]

********** Online boarding **********

[3 5 2 1 4 0]

********** Seat comfort **********

[5 1 2 3 4 0]

********** Inflight entertainment **********

[5 1 2 3 4 0]

********** On-board service **********

[4 1 2 3 5 0]

********** Leg room service **********

[3 5 4 2 1 0]

********** Baggage handling **********

[4 3 5 1 2]

********** Checkin service **********

[4 1 3 5 2 0]

********** Inflight service **********

[5 4 3 1 2 0]

********** Cleanliness **********

[5 1 2 3 4 0]

********** Departure Delay in Minutes **********

[  25    1    0   11    9    4   28   43   49    7   17   52   54   27
   18   19    3  109   23    8   14   10   51   39   13   30   64   20
   45   44   31   81   35   67   22   40   91   21   15   29  105   12
  162   24  141    6   34    2   97   16   99   37   66   53   36  209
   60  149   26    5   59   62  113   38   83  176   46   73  199   56
   93   70   80   96   57   95   74  172   63  175  143   48   47  101
  118   76  220   33   55  232  170  173  124  112   94  243  128   92
  270   90  110   50  144   71  315  158   88   65  111   32  156   41
  154  150  228   72  137  126  161   42  174  103  313  136  160  412
   69  185  114  135  142  147   85  235  125  391   84  138  102  196
  140   77  187  131   82  100   86  165   87  129  204  435  166  177
  123  139  116  108  167  285   61  117  106  190  168  211   89  324
   75  202  290  189  203  120  157  119   68  299  292   78  258  104
  121   58  222  317  320  200  134  248   79  240  169   98  249  145
  238  246  132  107  127  180  151  480  241  130  268  115  133  171
  164  330  438  472  163  122  326  186  155  223  332  447 1305  208
  201  233  210  182  221  159  188  184  224  178  266  191  219  652
  148  226  236  153  276  212  152  198  245  726  302  283  505  242
  215  394  206  311  293  566  225  146  218  227  252  291  193  323
  281  287  339  183  259  192  319  207  195  179  194  537  181  257
  213  300  295  262  312  383  392  294  250  419  216  308  423  346
  272  197  205  303  251  344  333  355  454  459  269  254  231  253
  265  301  263  381  214  310  244  239  255  328  348  278  859  692
  321  465  426  340  274  267  519  286  414  559  382  237  260  401
  247  376  288  271  450  230  217  279  264  448  398  750  365  316
  351  327  341  306  353  358  514  334  277  275  352  371  437  229
  600  296  460  338  307  234  289  452  318  256  368  626  729  362
  360  853  446  399  396  463  364  342  372  298  273  427  429  373
  420  579  930 1017  921  370  378  595  491  469  345  410  610  388
  748  336  433  455  347  444  282  978  322  496  389  359  415  329
  933  402  331  280  407 1592  501  384  377  503  400  430  570  357
  350  297  309  531  304  363  411  390  314  343  724  337  493  416
  951  366  284  489  404  794  431  590  305  499 1128  815  581  624
  569  756  565  530]

********** Arrival Delay in Minutes **********

[1.800e+01 6.000e+00 0.000e+00 9.000e+00 2.300e+01 8.000e+00 3.500e+01
 5.100e+01 1.000e+01 5.000e+00 4.000e+00 2.900e+01 4.400e+01 2.800e+01
 1.200e+01 1.200e+02 2.400e+01 1.000e+00 2.000e+01 3.100e+01 1.500e+01
 4.800e+01 2.600e+01 4.900e+01 2.000e+00 3.700e+01 5.000e+01 3.000e+00
 1.900e+01 7.200e+01 1.100e+01 3.400e+01 6.200e+01 2.700e+01 5.200e+01
 1.300e+01 8.200e+01 3.000e+01 1.600e+01 7.000e+00 1.220e+02 1.790e+02
 1.250e+02 1.700e+01 8.900e+01 1.010e+02 1.400e+01 6.100e+01 3.200e+01
 3.300e+01 4.100e+01 1.910e+02 1.380e+02 5.300e+01 2.200e+01 5.700e+01
 6.500e+01 7.600e+01 1.070e+02 9.200e+01 1.640e+02 2.100e+01 4.000e+01
 5.500e+01 1.850e+02 6.300e+01 7.700e+01 8.600e+01 9.100e+01 1.000e+02
 5.400e+01 3.600e+01 7.000e+01 1.390e+02 6.700e+01 1.630e+02 1.280e+02
 1.800e+02 9.300e+01 1.210e+02 4.500e+01 1.050e+02 1.260e+02 5.600e+01
 7.300e+01 2.120e+02 8.800e+01 2.410e+02 1.720e+02 1.750e+02 1.110e+02
 9.900e+01 2.500e+01 4.200e+01 2.260e+02 4.600e+01 1.310e+02 2.600e+02
 6.900e+01 1.420e+02 5.800e+01 7.500e+01 3.800e+01 6.600e+01 3.900e+01
 1.030e+02 3.070e+02 1.560e+02 7.400e+01 1.090e+02 1.550e+02 6.000e+01
 1.540e+02 4.300e+01 1.470e+02 2.170e+02 1.240e+02 4.700e+01 1.500e+02
 1.160e+02 1.710e+02 8.400e+01 1.230e+02 1.650e+02 9.400e+01 8.300e+01
 3.360e+02 5.900e+01 2.190e+02 8.700e+01 4.590e+02 6.800e+01 1.040e+02
 1.330e+02 1.340e+02 8.100e+01 2.590e+02 8.000e+01 7.900e+01 2.220e+02
 2.030e+02 3.540e+02 2.140e+02 7.800e+01 9.500e+01 7.100e+01 1.100e+02
 8.500e+01 1.460e+02 1.960e+02 9.800e+01 4.700e+02 2.640e+02 1.490e+02
 1.130e+02 1.190e+02 1.060e+02 2.160e+02 1.600e+02 2.850e+02 1.150e+02
 1.860e+02 2.110e+02 3.230e+02 1.760e+02 1.670e+02 2.420e+02 2.840e+02
 2.000e+02 1.450e+02 1.080e+02 1.740e+02 1.320e+02 3.130e+02 3.310e+02
 2.880e+02 1.180e+02 2.250e+02 6.400e+01 3.240e+02 1.900e+02 1.770e+02
 1.360e+02 3.200e+02 2.010e+02 2.710e+02 9.600e+01 1.520e+02 2.800e+02
 1.410e+02 1.570e+02 1.530e+02 1.300e+02 1.400e+02 1.120e+02 2.570e+02
 1.170e+02 2.350e+02 9.000e+01 1.810e+02 1.830e+02 1.270e+02 4.710e+02
 2.270e+02 1.020e+02 1.350e+02 1.290e+02 2.550e+02 1.920e+02 3.480e+02
 4.380e+02 4.460e+02 1.840e+02 1.680e+02 1.660e+02 3.100e+02 1.730e+02
 2.610e+02 1.610e+02 2.360e+02 1.510e+02 1.820e+02 3.210e+02 2.330e+02
 1.370e+02 4.330e+02 1.280e+03 2.180e+02 1.480e+02 1.440e+02 1.870e+02
 2.060e+02 1.700e+02 2.090e+02 1.140e+02 2.240e+02 2.810e+02 2.230e+02
 6.380e+02 2.200e+02 2.340e+02 9.700e+01 2.650e+02 3.880e+02 2.620e+02
 2.210e+02 1.620e+02 2.670e+02 3.740e+02 2.280e+02 2.440e+02 2.470e+02
 6.910e+02 1.430e+02 1.890e+02 1.970e+02 2.040e+02 3.190e+02 2.730e+02
 3.290e+02 1.950e+02 4.860e+02 1.780e+02 2.700e+02 1.580e+02 1.990e+02
 2.130e+02 3.830e+02 3.020e+02 6.000e+02 2.150e+02 1.690e+02 1.880e+02
 2.660e+02 2.920e+02 2.870e+02 2.300e+02 2.390e+02 2.890e+02 2.980e+02
 2.320e+02 3.630e+02 2.050e+02 2.950e+02 2.830e+02 5.240e+02 3.270e+02
 2.460e+02 2.900e+02 3.140e+02 3.160e+02 3.040e+02 2.020e+02 2.960e+02
 2.480e+02 3.860e+02 3.810e+02 1.590e+02 3.220e+02 4.600e+02 4.180e+02
 3.490e+02 2.560e+02 2.490e+02 1.940e+02 3.150e+02 2.080e+02 1.930e+02
 3.710e+02 2.290e+02 3.910e+02 4.540e+02 4.450e+02 2.100e+02 2.680e+02
 2.530e+02 2.450e+02 3.370e+02 2.970e+02 4.360e+02 2.790e+02 3.000e+02
 2.400e+02 2.370e+02 2.070e+02 1.980e+02 4.040e+02 2.430e+02 3.410e+02
 2.780e+02 3.050e+02 8.600e+02 2.580e+02 7.020e+02 3.600e+02 4.930e+02
 4.270e+02 3.350e+02 5.160e+02 2.720e+02 4.100e+02 5.550e+02 3.920e+02
 2.520e+02 3.300e+02 3.820e+02 2.930e+02 2.770e+02 2.310e+02 2.750e+02
 3.620e+02 2.760e+02 7.290e+02 3.570e+02 3.260e+02 2.500e+02 4.580e+02
 3.340e+02 2.910e+02 3.800e+02 3.590e+02 3.460e+02 6.240e+02 3.770e+02
 3.720e+02 4.290e+02 5.890e+02 3.010e+02 5.020e+02 2.990e+02 4.570e+02
 2.380e+02 4.010e+02 4.400e+02 2.860e+02 2.740e+02 3.110e+02 3.030e+02
 6.040e+02 7.170e+02 3.560e+02 4.090e+02 8.230e+02 2.940e+02 2.510e+02
 4.310e+02 4.320e+02 4.030e+02 3.180e+02 5.030e+02 3.380e+02 3.640e+02
 4.070e+02 3.680e+02 3.080e+02 2.540e+02 4.350e+02 2.630e+02 4.170e+02
 3.580e+02 4.160e+02 5.610e+02 3.510e+02 9.520e+02 1.011e+03 9.240e+02
 3.060e+02 4.240e+02 4.850e+02 4.430e+02 3.170e+02 5.180e+02 3.500e+02
 4.440e+02 3.120e+02 3.970e+02 5.930e+02 3.930e+02 7.200e+02 3.660e+02
 4.550e+02 2.690e+02 4.340e+02 9.700e+02 3.470e+02 3.090e+02 3.780e+02
 3.790e+02 3.950e+02 3.700e+02 4.480e+02 9.200e+02 3.890e+02 3.550e+02
 3.420e+02 1.584e+03 5.000e+02 4.020e+02 4.060e+02 4.840e+02 4.120e+02
 5.670e+02 4.200e+02 3.990e+02 3.450e+02 3.530e+02 4.220e+02 2.820e+02
 5.070e+02 4.250e+02 3.390e+02 3.520e+02 3.850e+02 7.050e+02 3.690e+02
 9.400e+02 3.440e+02 4.910e+02 4.130e+02 3.250e+02 7.950e+02 6.080e+02
 4.000e+02 4.730e+02 1.115e+03 8.220e+02 5.800e+02 6.150e+02 5.430e+02
 7.480e+02 5.860e+02 3.330e+02]

********** satisfaction **********

['neutral or dissatisfied' 'satisfied']

In [13]:
count =0
for i in df:
    if " " or "" in df[i]:
        count+=1

In [14]:
count

25

In [15]:
# Replace empty strings and whitespace-only strings with NaN across the whole DataFrame
df = df.replace(r'^\s*$', np.nan, regex=True)

# Now check missing values properly
print(df.isnull().sum())

Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [16]:
count =0
for i in df:
    if " " or "" in df[i]:
        count+=1

In [17]:
count

25

In [18]:
for i in df:
    if df[i] == " ":
        df[i].replace(" ",np.nan)
    elif df[i] =="":
        df[i].replace("",np.nan)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [19]:
import numpy as np

for i in df.columns:
    df[i] = df[i].replace(" ", np.nan)
    df[i] = df[i].replace("", np.nan)

In [20]:
df.isnull().sum()

Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [21]:
count =0
for i in df:
    if " " in df[i]:
        count+=1

In [22]:
count

0

In [23]:
df[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, id, Gender, Customer Type, Age, Type of Travel, Class, Flight Distance, Inflight wifi service, Departure/Arrival time convenient, Ease of Online booking, Gate location, Food and drink, Online boarding, Seat comfort, Inflight entertainment, On-board service, Leg room service, Baggage handling, Checkin service, Inflight service, Cleanliness, Departure Delay in Minutes, Arrival Delay in Minutes, satisfaction]
Index: []

[0 rows x 25 columns]

In [24]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [25]:
df.head(2)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied

# Spliting the Data X[inputs] & y[target variable]

In [26]:
X = df.drop(['Unnamed: 0', 'id','satisfaction'], axis=1)

In [27]:
X.head()

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,1,...,5,5,4,3,4,4,5,5,25,18.0
1,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,3,...,1,1,1,5,3,1,4,1,1,6.0
2,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,2,...,5,5,4,3,4,4,4,5,0,0.0
3,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,5,...,2,2,2,5,3,1,4,2,11,9.0
4,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,3,...,5,3,3,4,4,3,3,3,0,0.0

In [28]:
y = df[['satisfaction']]

In [29]:
y.head()

              satisfaction
0  neutral or dissatisfied
1  neutral or dissatisfied
2                satisfied
3  neutral or dissatisfied
4                satisfied

# Seperation of train and test data

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state = 42)

In [31]:
X_train

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
21413,Female,Loyal Customer,64,Personal Travel,Business,965,3,5,3,3,...,5,1,1,3,1,5,1,5,11,4.0
7284,Male,disloyal Customer,26,Business travel,Business,592,2,1,1,2,...,3,3,5,4,5,4,4,3,112,125.0
86080,Female,Loyal Customer,8,Personal Travel,Eco,993,3,4,3,1,...,4,4,4,5,5,4,4,4,0,0.0
59842,Male,Loyal Customer,41,Business travel,Business,2223,4,4,4,4,...,4,5,5,5,5,5,5,1,9,4.0
69486,Female,disloyal Customer,19,Business travel,Eco,1235,4,4,4,4,...,3,3,1,2,4,1,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128106,Female,Loyal Customer,38,Business travel,Eco,907,4,4,4,4,...,4,4,2,5,1,2,4,4,0,0.0
103694,Male,Loyal Customer,46,Business travel,Eco,1197,1,2,2,2,...,1,4,3,3,3,1,1,1,260,263.0
860,Female,Loyal Customer,37,Business travel,Eco,320,5,5,5,5,...,5,5,1,2,4,1,3,5,0,0.0
15795,Female,Loyal Customer,14,Personal Travel,Eco,351,4,5,4,2,...,4,4,3,5,5,4,4,4,0,0.0
121958,Male,Loyal Customer,34,Business travel,Eco,867,2,4,4,4,...,2,2,4,4,4,4,3,2,0,0.0

In [32]:
X_test

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
103044,Male,Loyal Customer,66,Personal Travel,Eco,1678,3,2,3,2,...,4,4,4,3,2,3,2,4,0,0.0
43282,Female,Loyal Customer,38,Business travel,Business,954,2,2,2,2,...,1,4,4,4,4,2,4,4,3,0.0
65543,Female,Loyal Customer,38,Business travel,Eco,189,2,1,1,1,...,2,2,1,2,4,1,4,2,0,0.0
65083,Female,Loyal Customer,32,Personal Travel,Eco,175,2,5,2,1,...,1,1,3,5,4,5,4,1,0,0.0
76496,Male,Loyal Customer,33,Business travel,Business,1990,5,5,5,5,...,4,4,4,1,5,5,1,4,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121239,Female,Loyal Customer,44,Personal Travel,Eco,264,4,1,4,2,...,2,4,4,4,4,3,4,4,0,0.0
6010,Female,Loyal Customer,53,Business travel,Business,2248,5,5,5,5,...,5,5,5,5,5,5,5,3,4,0.0
101127,Male,Loyal Customer,28,Business travel,Eco Plus,489,4,5,5,5,...,4,4,3,2,5,3,4,4,2,0.0
82323,Male,Loyal Customer,30,Business travel,Business,448,2,2,2,2,...,5,5,4,4,4,5,4,5,90,97.0
61871,Female,Loyal Customer,59,Personal Travel,Eco,1721,3,3,3,4,...,4,4,4,3,4,1,4,3,9,0.0

In [33]:
y_train

                   satisfaction
21413   neutral or dissatisfied
7284    neutral or dissatisfied
86080   neutral or dissatisfied
59842                 satisfied
69486   neutral or dissatisfied
...                         ...
128106                satisfied
103694  neutral or dissatisfied
860                   satisfied
15795   neutral or dissatisfied
121958  neutral or dissatisfied

[103904 rows x 1 columns]

In [34]:
y_test

                   satisfaction
103044  neutral or dissatisfied
43282                 satisfied
65543   neutral or dissatisfied
65083   neutral or dissatisfied
76496                 satisfied
...                         ...
121239  neutral or dissatisfied
6010                  satisfied
101127                satisfied
82323                 satisfied
61871   neutral or dissatisfied

[25976 rows x 1 columns]

In [35]:
cat_df = X_train[['Gender','Customer Type','Type of Travel']]

In [36]:
cat_df

        Gender      Customer Type   Type of Travel
21413   Female     Loyal Customer  Personal Travel
7284      Male  disloyal Customer  Business travel
86080   Female     Loyal Customer  Personal Travel
59842     Male     Loyal Customer  Business travel
69486   Female  disloyal Customer  Business travel
...        ...                ...              ...
128106  Female     Loyal Customer  Business travel
103694    Male     Loyal Customer  Business travel
860     Female     Loyal Customer  Business travel
15795   Female     Loyal Customer  Personal Travel
121958    Male     Loyal Customer  Business travel

[103904 rows x 3 columns]

In [37]:
cato_df = X_train[['Class']]

In [38]:
cato_df

           Class
21413   Business
7284    Business
86080        Eco
59842   Business
69486        Eco
...          ...
128106       Eco
103694       Eco
860          Eco
15795        Eco
121958       Eco

[103904 rows x 1 columns]

In [39]:
num_df = X_train.select_dtypes(include = 'number')

In [40]:
num_df

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
21413,64,965,3,5,3,3,5,5,5,1,1,3,1,5,1,5,11,4.0
7284,26,592,2,1,1,2,3,1,3,3,5,4,5,4,4,3,112,125.0
86080,8,993,3,4,3,1,4,3,4,4,4,5,5,4,4,4,0,0.0
59842,41,2223,4,4,4,4,1,2,4,5,5,5,5,5,5,1,9,4.0
69486,19,1235,4,4,4,4,3,4,3,3,1,2,4,1,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128106,38,907,4,4,4,4,4,4,4,4,2,5,1,2,4,4,0,0.0
103694,46,1197,1,2,2,2,1,1,1,4,3,3,3,1,1,1,260,263.0
860,37,320,5,5,5,5,5,5,5,5,1,2,4,1,3,5,0,0.0
15795,14,351,4,5,4,2,4,4,4,4,3,5,5,4,4,4,0,0.0
121958,34,867,2,4,4,4,2,2,2,2,4,4,4,4,3,2,0,0.0

In [41]:
for i in num_df:
    print("*"*10,i,"*"*10)
    print()
    print(num_df[i].unique())
    print()

********** Age **********

[64 26  8 41 19 47 40 18 38 24 29 35 45 60 62 49 39 27 37 22 57 61 42 46
 65 52 17 50 20 66 36 30 23 55 43 67  9 58 25 34 44 54 28 15 21 69 12 56
 48 13 51  7 59 31 70 77 16 80 85 33 32 11 72 53 10 63 14 68 75 71 73 76
 78 74 79]

********** Flight Distance **********

[ 965  592  993 ... 1441 1343  905]

********** Inflight wifi service **********

[3 2 4 5 1 0]

********** Departure/Arrival time convenient **********

[5 1 4 3 2 0]

********** Ease of Online booking **********

[3 1 4 2 5 0]

********** Gate location **********

[3 2 1 4 5 0]

********** Food and drink **********

[5 3 4 1 2 0]

********** Online boarding **********

[5 1 3 2 4 0]

********** Seat comfort **********

[5 3 4 2 1 0]

********** Inflight entertainment **********

[1 3 4 5 2 0]

********** On-board service **********

[1 5 4 2 3 0]

********** Leg room service **********

[3 4 5 2 1 0]

********** Baggage handling **********

[1 5 4 3 2]

********** Checkin service **********

[5 4 1 2 3 0]

********** Inflight service **********

[1 4 5 3 2 0]

********** Cleanliness **********

[5 3 4 1 2 0]

********** Departure Delay in Minutes **********

[  11  112    0    9   83    1    8   27   21   10  127   49    6   13
   24   66   53   14   74    4  360   12   16  104  291    5   20    2
    7   36   15  274   32  142   60   58   19   57   35   61   41   64
   73   42  264    3   18  109   48   22  160   56   39   55   54   75
   17  111   34   38   31   28   52  132  107   46   86   76   33   45
   63   43   71   26  221   37  149   30   72   94   91   92   50  118
   40  129  166   59   47   87  114   51   25   68  137   23  105  173
  151   77  115  324   97  103  100   29  200   96   84   70   78  192
  194   98   85  144  186  254  351  164  179  117   93  238  134  119
  212  154   82   90  267  145  182  110  125   80  301  106  237   81
  273  365  158  148  180  133   88  175  205  153   62   65  140   44
  201  162  116  113  275   79  108   99   95  266  226  211  206  978
  171  271  244  126  121  165  340  610  120  209  146   67  210  214
  228  157  318  283  184  102  224  420  204  358  197  161  155  167
  178   89  152  202  168   69  136  415  190 1128  185  123  272  183
  207  198  130  930  150  241  215  131  330  310  279  294  156  247
  188  191  250  196  176  276  181  177  139  231  170  344  265  327
  138  159  447  141  124  213  370  341  187  531  143  101  232  234
  242  174  259  239  193  240  122  128  249  217  195  218  514  419
  326  353  147  172  199  652  338  169  313  135  230  229  302  219
  398  423  281  223  236  289  163  350  300  248  569  245  579  590
  255  402  258  208  355  280  299  624  233  320  262  298  382  290
  427  348  253  815  235  363  222  394  287  412  411  288  189  282
  270  430  438  357  384  243  352  292  220  519  225  724  454  312
  293  465  315  286  377  389  295  414  322  203  334  285  469  216
  328  381  333  401  307  505  410  452  493  316  303  277  921  566
  269  332  319  581  311  489  933  346  252  308  726  359  392  297
  296  437  383  748  951  503  373  391  364  400  314  480  491  859
  227  595  256  268  339  396  435  251  368  426  337  284  345 1305
  626  692  343  499  246  378  448  336  404  416  407  496  366  257
  342  750  317  323  459  729  304  756  263  600  260  372  347  362
  306  278  460  463  399  429  433  501  329  472  565  305  331  390
  431  450  853  530]

********** Arrival Delay in Minutes **********

[4.000e+00 1.250e+02 0.000e+00 7.300e+01 3.000e+00 1.000e+00 1.300e+01
 2.300e+01 5.000e+00 1.290e+02 5.300e+01 3.900e+01 2.000e+01 5.800e+01
 6.000e+00 4.100e+01 1.800e+01 8.000e+00 9.100e+01 2.000e+00 3.470e+02
 1.400e+01 1.000e+01 2.900e+01 8.600e+01 2.920e+02 2.400e+01 9.000e+00
 2.640e+02 2.500e+01 1.370e+02 7.000e+01 4.300e+01 1.900e+01 1.100e+01
 6.500e+01 4.800e+01 4.400e+01 8.800e+01 8.100e+01 4.700e+01 2.880e+02
 1.080e+02 4.900e+01 6.000e+01 7.000e+00 1.200e+01 1.340e+02 3.400e+01
 3.100e+01 1.710e+02 1.700e+01 4.600e+01 1.150e+02 1.600e+01 8.000e+01
 2.100e+01 5.700e+01 2.600e+01 1.170e+02 1.300e+02 9.000e+01 3.300e+01
 5.900e+01 7.200e+01 3.500e+01 4.000e+01 6.300e+01 6.700e+01 1.240e+02
 3.600e+01 2.170e+02 3.700e+01 2.700e+01 3.000e+01 6.800e+01 1.520e+02
 7.400e+01 4.500e+01 5.500e+01 1.680e+02 2.200e+01 1.500e+01 9.200e+01
 1.020e+02 9.900e+01 1.070e+02 4.200e+01 1.640e+02 3.200e+01 1.480e+02
 9.400e+01 6.600e+01 1.350e+02 1.740e+02 1.420e+02 1.090e+02 3.070e+02
 5.600e+01 1.030e+02 8.700e+01 2.250e+02 8.300e+01 1.920e+02 2.800e+01
 7.600e+01 3.800e+01 2.930e+02 2.110e+02 1.270e+02 7.700e+01 7.500e+01
 1.050e+02 2.390e+02 3.930e+02 1.430e+02 1.720e+02 7.100e+01 1.000e+02
 2.320e+02 1.360e+02 5.400e+01 8.400e+01 7.900e+01 5.200e+01 1.400e+02
 6.200e+01 2.840e+02 1.390e+02 1.040e+02 2.890e+02 8.500e+01 2.440e+02
 1.190e+02 8.900e+01 2.590e+02 5.100e+01 3.570e+02 1.450e+02 1.600e+02
 7.800e+01 5.000e+01 6.100e+01 1.820e+02 1.140e+02 2.210e+02 1.410e+02
 1.130e+02 6.900e+01 1.210e+02 1.800e+02 9.500e+01 1.960e+02 6.400e+01
 8.200e+01 1.510e+02 1.180e+02 1.860e+02 1.570e+02 9.300e+01 2.760e+02
 1.470e+02 2.580e+02 2.340e+02 1.690e+02 2.430e+02 1.650e+02 9.700e+02
 1.790e+02 1.990e+02 1.200e+02 2.500e+02 2.360e+02 1.100e+02 1.280e+02
 1.110e+02 1.850e+02 1.010e+02 1.670e+02 3.380e+02 1.950e+02 5.930e+02
 2.280e+02 2.030e+02 9.800e+01 2.300e+02 3.010e+02 1.560e+02 1.220e+02
 2.050e+02 4.160e+02 3.460e+02 1.890e+02 1.230e+02 1.490e+02 1.590e+02
 1.880e+02 2.550e+02 1.460e+02 1.440e+02 1.320e+02 4.100e+02 1.115e+03
 1.830e+02 1.620e+02 1.610e+02 9.700e+01 2.700e+02 2.670e+02 1.530e+02
 1.540e+02 4.090e+02 2.080e+02 1.160e+02 1.780e+02 2.060e+02 9.520e+02
 2.610e+02 1.500e+02 3.220e+02 9.600e+01 1.120e+02 3.050e+02 1.700e+02
 1.380e+02 2.520e+02 2.810e+02 1.750e+02 1.330e+02 2.160e+02 1.900e+02
 1.870e+02 2.510e+02 2.480e+02 2.350e+02 2.190e+02 3.190e+02 2.070e+02
 1.940e+02 2.310e+02 3.260e+02 3.170e+02 4.380e+02 1.060e+02 1.660e+02
 2.040e+02 3.410e+02 3.340e+02 1.840e+02 4.850e+02 1.550e+02 2.530e+02
 2.630e+02 2.380e+02 2.980e+02 1.770e+02 1.580e+02 2.240e+02 2.200e+02
 1.310e+02 3.130e+02 2.180e+02 1.980e+02 1.260e+02 2.140e+02 2.290e+02
 6.240e+02 4.600e+02 3.660e+02 3.590e+02 2.540e+02 6.380e+02 3.330e+02
 2.460e+02 1.970e+02 3.360e+02 2.400e+02 3.160e+02 3.120e+02 3.140e+02
 3.770e+02 4.170e+02 2.150e+02 2.020e+02 1.930e+02 2.940e+02 2.260e+02
 1.760e+02 3.090e+02 3.180e+02 2.620e+02 2.000e+02 5.430e+02 5.610e+02
 6.080e+02 3.740e+02 1.910e+02 3.290e+02 3.890e+02 2.130e+02 2.850e+02
 6.150e+02 2.740e+02 3.200e+02 2.100e+02 2.330e+02 2.090e+02 2.120e+02
 2.960e+02 2.710e+02 3.720e+02 2.900e+02 4.400e+02 3.000e+02 3.240e+02
 2.570e+02 2.220e+02 8.220e+02 2.230e+02 3.500e+02 2.370e+02 3.620e+02
 2.560e+02 2.720e+02 1.630e+02 4.590e+02 4.250e+02 2.790e+02 1.810e+02
 3.030e+02 2.600e+02 1.730e+02 4.020e+02 3.310e+02 3.040e+02 5.160e+02
 7.050e+02 4.480e+02 3.100e+02 2.650e+02 2.820e+02 4.930e+02 2.750e+02
 3.680e+02 4.200e+02 3.910e+02 3.350e+02 2.990e+02 2.780e+02 3.830e+02
 2.860e+02 4.040e+02 4.360e+02 3.800e+02 5.020e+02 4.860e+02 4.350e+02
 2.870e+02 2.010e+02 3.690e+02 9.240e+02 6.000e+02 4.430e+02 3.210e+02
 3.630e+02 5.800e+02 2.770e+02 2.270e+02 4.910e+02 3.020e+02 9.200e+02
 2.680e+02 3.490e+02 2.450e+02 2.970e+02 2.410e+02 6.910e+02 3.790e+02
 3.810e+02 5.180e+02 4.010e+02 7.200e+02 9.400e+02 4.840e+02 3.580e+02
 3.540e+02 2.830e+02 3.520e+02 4.540e+02 3.270e+02 2.800e+02 3.110e+02
 3.550e+02 4.120e+02 4.710e+02 4.330e+02 8.600e+02 2.470e+02 2.660e+02
 5.070e+02 5.890e+02 4.030e+02 4.700e+02 2.490e+02 4.220e+02 3.420e+02
 4.270e+02 3.300e+02 3.080e+02 4.070e+02 1.280e+03 6.040e+02 7.020e+02
 3.990e+02 3.710e+02 3.920e+02 4.730e+02 4.240e+02 4.450e+02 3.230e+02
 4.130e+02 2.420e+02 2.950e+02 3.510e+02 3.640e+02 3.880e+02 2.910e+02
 7.290e+02 3.780e+02 3.450e+02 7.170e+02 2.730e+02 7.480e+02 3.850e+02
 4.180e+02 3.060e+02 4.570e+02 5.030e+02 4.320e+02 4.550e+02 3.970e+02
 5.000e+02 3.950e+02 4.460e+02 5.860e+02 3.480e+02 8.230e+02]

In [42]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(sparse_output=False).set_output(transform = 'pandas')
cat_df_trans = OHE.fit_transform(cat_df)

In [43]:
cat_df_trans

,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel
21413,1.0,0.0,1.0,0.0,0.0,1.0
7284,0.0,1.0,0.0,1.0,1.0,0.0
86080,1.0,0.0,1.0,0.0,0.0,1.0
59842,0.0,1.0,1.0,0.0,1.0,0.0
69486,1.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...
128106,1.0,0.0,1.0,0.0,1.0,0.0
103694,0.0,1.0,1.0,0.0,1.0,0.0
860,1.0,0.0,1.0,0.0,1.0,0.0
15795,1.0,0.0,1.0,0.0,0.0,1.0
121958,0.0,1.0,1.0,0.0,1.0,0.0

In [44]:
from sklearn.preprocessing import OrdinalEncoder
OE = OrdinalEncoder().set_output(transform='pandas')
cato_df_trans  = OE.fit_transform(cato_df)

In [45]:
cato_df_trans

        Class
21413     0.0
7284      0.0
86080     1.0
59842     0.0
69486     1.0
...       ...
128106    1.0
103694    1.0
860       1.0
15795     1.0
121958    1.0

[103904 rows x 1 columns]

In [46]:
from sklearn.preprocessing import StandardScaler

STD = StandardScaler().set_output(transform = 'pandas')

num_df_trans = STD.fit_transform(num_df)

In [47]:
num_df_trans

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
21413,1.626500,-0.224186,0.206148,1.271199,0.174602,0.016243,1.351802,1.293331,1.182388,-1.766908,-1.850069,-0.267017,-2.232966,1.339067,-2.249827,1.305686,-0.098242,-0.287436
7284,-0.886203,-0.598714,-0.545787,-1.349410,-1.250971,-0.767277,-0.153268,-1.665458,-0.333637,-0.267887,1.254828,0.493055,1.158966,0.548926,0.301870,-0.218814,2.552090,2.858685
86080,-2.076430,-0.196071,0.206148,0.616046,0.174602,-1.550797,0.599267,-0.186063,0.424376,0.481623,0.478603,1.253128,1.158966,0.548926,0.301870,0.543436,-0.386892,-0.391440
59842,0.105653,1.038969,0.958084,0.616046,0.887389,0.799763,-1.658337,-0.925760,0.424376,1.231133,1.254828,1.253128,1.158966,1.339067,1.152435,-1.743314,-0.150724,-0.287436
69486,-1.349069,0.046920,0.958084,0.616046,0.887389,0.799763,-0.153268,0.553634,-0.333637,-0.267887,-1.850069,-1.027090,0.310983,-1.821499,0.301870,-0.218814,-0.386892,-0.391440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128106,-0.092718,-0.282424,0.958084,0.616046,0.887389,0.799763,0.599267,0.553634,0.424376,0.481623,-1.073845,1.253128,-2.232966,-1.031357,0.301870,0.543436,-0.386892,-0.391440
103694,0.436272,0.008765,-1.297723,-0.694258,-0.538185,-0.767277,-1.658337,-1.665458,-1.849662,0.481623,-0.297621,-0.267017,-0.537000,-1.821499,-2.249827,-1.743314,6.435744,6.446824
860,-0.158842,-0.871829,1.710020,1.271199,1.600175,1.583283,1.351802,1.293331,1.182388,1.231133,-1.850069,-1.027090,0.310983,-1.821499,-0.548696,1.305686,-0.386892,-0.391440
15795,-1.679688,-0.840702,0.958084,1.271199,0.887389,-0.767277,0.599267,0.553634,0.424376,0.481623,-0.297621,1.253128,1.158966,0.548926,0.301870,0.543436,-0.386892,-0.391440
121958,-0.357213,-0.322588,-0.545787,0.616046,0.887389,0.799763,-0.905803,-0.925760,-1.091649,-1.017398,0.478603,0.493055,0.310983,0.548926,-0.548696,-0.981064,-0.386892,-0.391440

In [48]:
cat_df_trans.reset_index(inplace = True)

In [49]:
cato_df_trans.reset_index(inplace = True)

In [50]:
num_df_trans.reset_index(inplace = True)

In [51]:
X_train_trans = pd.concat([cat_df_trans,cato_df_trans,num_df_trans],axis=1)

In [52]:
X_train_trans

,index,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel,index,Class,index,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,21413,1.0,0.0,1.0,0.0,0.0,1.0,21413,0.0,21413,...,1.182388,-1.766908,-1.850069,-0.267017,-2.232966,1.339067,-2.249827,1.305686,-0.098242,-0.287436
1,7284,0.0,1.0,0.0,1.0,1.0,0.0,7284,0.0,7284,...,-0.333637,-0.267887,1.254828,0.493055,1.158966,0.548926,0.301870,-0.218814,2.552090,2.858685
2,86080,1.0,0.0,1.0,0.0,0.0,1.0,86080,1.0,86080,...,0.424376,0.481623,0.478603,1.253128,1.158966,0.548926,0.301870,0.543436,-0.386892,-0.391440
3,59842,0.0,1.0,1.0,0.0,1.0,0.0,59842,0.0,59842,...,0.424376,1.231133,1.254828,1.253128,1.158966,1.339067,1.152435,-1.743314,-0.150724,-0.287436
4,69486,1.0,0.0,0.0,1.0,1.0,0.0,69486,1.0,69486,...,-0.333637,-0.267887,-1.850069,-1.027090,0.310983,-1.821499,0.301870,-0.218814,-0.386892,-0.391440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,128106,1.0,0.0,1.0,0.0,1.0,0.0,128106,1.0,128106,...,0.424376,0.481623,-1.073845,1.253128,-2.232966,-1.031357,0.301870,0.543436,-0.386892,-0.391440
103900,103694,0.0,1.0,1.0,0.0,1.0,0.0,103694,1.0,103694,...,-1.849662,0.481623,-0.297621,-0.267017,-0.537000,-1.821499,-2.249827,-1.743314,6.435744,6.446824
103901,860,1.0,0.0,1.0,0.0,1.0,0.0,860,1.0,860,...,1.182388,1.231133,-1.850069,-1.027090,0.310983,-1.821499,-0.548696,1.305686,-0.386892,-0.391440
103902,15795,1.0,0.0,1.0,0.0,0.0,1.0,15795,1.0,15795,...,0.424376,0.481623,-0.297621,1.253128,1.158966,0.548926,0.301870,0.543436,-0.386892,-0.391440
103903,121958,0.0,1.0,1.0,0.0,1.0,0.0,121958,1.0,121958,...,-1.091649,-1.017398,0.478603,0.493055,0.310983,0.548926,-0.548696,-0.981064,-0.386892,-0.391440

In [53]:
X_train_trans.pop('index')

         index   index   index
0        21413   21413   21413
1         7284    7284    7284
2        86080   86080   86080
3        59842   59842   59842
4        69486   69486   69486
...        ...     ...     ...
103899  128106  128106  128106
103900  103694  103694  103694
103901     860     860     860
103902   15795   15795   15795
103903  121958  121958  121958

[103904 rows x 3 columns]

In [54]:
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

y_train_trans = LE.fit_transform(y_train)

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [55]:
y_train_trans

array([0, 0, 0, ..., 1, 0, 0], shape=(103904,))

In [56]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

y_train_trans = pd.DataFrame(
    LE.fit_transform(y_train),
    index=y_train.index   # keeps the original row indices aligned
)

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [57]:
y_train_trans

        0
21413   0
7284    0
86080   0
59842   1
69486   0
...    ..
128106  1
103694  0
860     1
15795   0
121958  0

[103904 rows x 1 columns]

In [58]:
y_train_trans.reset_index(inplace = True)

In [59]:
y_train_trans

         index  0
0        21413  0
1         7284  0
2        86080  0
3        59842  1
4        69486  0
...        ... ..
103899  128106  1
103900  103694  0
103901     860  1
103902   15795  0
103903  121958  0

[103904 rows x 2 columns]

In [60]:
y_train_trans.pop('index')

0          21413
1           7284
2          86080
3          59842
4          69486
           ...
103899    128106
103900    103694
103901       860
103902     15795
103903    121958
Name: index, Length: 103904, dtype: int64

In [61]:
cat_df = X_test[['Gender','Customer Type','Type of Travel']]

In [62]:
cato_df = X_test[['Class']]

In [63]:
num_df = X_test.select_dtypes(include = 'number')

In [64]:
cat_df

        Gender   Customer Type   Type of Travel
103044    Male  Loyal Customer  Personal Travel
43282   Female  Loyal Customer  Business travel
65543   Female  Loyal Customer  Business travel
65083   Female  Loyal Customer  Personal Travel
76496     Male  Loyal Customer  Business travel
...        ...             ...              ...
121239  Female  Loyal Customer  Personal Travel
6010    Female  Loyal Customer  Business travel
101127    Male  Loyal Customer  Business travel
82323     Male  Loyal Customer  Business travel
61871   Female  Loyal Customer  Personal Travel

[25976 rows x 3 columns]

In [65]:
cato_df

           Class
103044       Eco
43282   Business
65543        Eco
65083        Eco
76496   Business
...          ...
121239       Eco
6010    Business
101127  Eco Plus
82323   Business
61871        Eco

[25976 rows x 1 columns]

In [66]:
num_df

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
103044,66,1678,3,2,3,2,4,3,4,4,4,3,2,3,2,4,0,0.0
43282,38,954,2,2,2,2,2,3,1,4,4,4,4,2,4,4,3,0.0
65543,38,189,2,1,1,1,2,2,2,2,1,2,4,1,4,2,0,0.0
65083,32,175,2,5,2,1,1,2,1,1,3,5,4,5,4,1,0,0.0
76496,33,1990,5,5,5,5,4,4,4,4,4,1,5,5,1,4,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121239,44,264,4,1,4,2,2,2,2,4,4,4,4,3,4,4,0,0.0
6010,53,2248,5,5,5,5,5,3,5,5,5,5,5,5,5,3,4,0.0
101127,28,489,4,5,5,5,4,4,4,4,3,2,5,3,4,4,2,0.0
82323,30,448,2,2,2,2,5,5,5,5,4,4,4,5,4,5,90,97.0
61871,59,1721,3,3,3,4,4,4,4,4,4,3,4,1,4,3,9,0.0

In [67]:
cat_df_trans = OHE.transform(cat_df)

In [68]:
cato_df_trans = OE.transform(cato_df)

In [69]:
num_df_trans = STD.transform(num_df)

In [70]:
cat_df_trans.reset_index(inplace = True)

In [71]:
cato_df_trans.reset_index(inplace = True)

In [72]:
num_df_trans.reset_index(inplace = True)

In [73]:
cat_df_trans

,index,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel
0,103044,0.0,1.0,1.0,0.0,0.0,1.0
1,43282,1.0,0.0,1.0,0.0,1.0,0.0
2,65543,1.0,0.0,1.0,0.0,1.0,0.0
3,65083,1.0,0.0,1.0,0.0,0.0,1.0
4,76496,0.0,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...
25971,121239,1.0,0.0,1.0,0.0,0.0,1.0
25972,6010,1.0,0.0,1.0,0.0,1.0,0.0
25973,101127,0.0,1.0,1.0,0.0,1.0,0.0
25974,82323,0.0,1.0,1.0,0.0,1.0,0.0
25975,61871,1.0,0.0,1.0,0.0,0.0,1.0

In [74]:
cato_df_trans

        index  Class
0      103044    1.0
1       43282    0.0
2       65543    1.0
3       65083    1.0
4       76496    0.0
...       ...    ...
25971  121239    1.0
25972    6010    0.0
25973  101127    2.0
25974   82323    0.0
25975   61871    1.0

[25976 rows x 2 columns]

In [75]:
num_df_trans

,index,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,103044,1.758747,0.491735,0.206148,-0.694258,0.174602,-0.767277,0.599267,-0.186063,0.424376,0.481623,0.478603,-0.267017,-1.384983,-0.241216,-1.399262,0.543436,-0.386892,-0.391440
1,43282,-0.092718,-0.235231,-0.545787,-0.694258,-0.538185,-0.767277,-0.905803,-0.186063,-1.849662,0.481623,0.478603,0.493055,0.310983,-1.031357,0.301870,0.543436,-0.308169,-0.391440
2,65543,-0.092718,-1.003366,-0.545787,-1.349410,-1.250971,-1.550797,-0.905803,-0.925760,-1.091649,-1.017398,-1.850069,-1.027090,0.310983,-1.821499,0.301870,-0.981064,-0.386892,-0.391440
3,65083,-0.489460,-1.017423,-0.545787,1.271199,-0.538185,-1.550797,-1.658337,-0.925760,-1.849662,-1.766908,-0.297621,1.253128,0.310983,1.339067,0.301870,-1.743314,-0.386892,-0.391440
4,76496,-0.423337,0.805014,1.710020,1.271199,1.600175,1.583283,0.599267,0.553634,0.424376,0.481623,0.478603,-1.787163,1.158966,1.339067,-2.249827,0.543436,-0.386892,-0.391440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,121239,0.304025,-0.928058,0.958084,-1.349410,0.887389,-0.767277,-0.905803,-0.925760,-1.091649,0.481623,0.478603,0.493055,0.310983,-0.241216,0.301870,0.543436,-0.386892,-0.391440
25972,6010,0.899138,1.064071,1.710020,1.271199,1.600175,1.583283,1.351802,-0.186063,1.182388,1.231133,1.254828,1.253128,1.158966,1.339067,1.152435,-0.218814,-0.281928,-0.391440
25973,101127,-0.753955,-0.702136,0.958084,1.271199,1.600175,1.583283,0.599267,0.553634,0.424376,0.481623,-0.297621,-1.027090,1.158966,-0.241216,0.301870,0.543436,-0.334410,-0.391440
25974,82323,-0.621708,-0.743304,-0.545787,-0.694258,-0.538185,-0.767277,1.351802,1.293331,1.182388,1.231133,0.478603,0.493055,0.310983,1.339067,0.301870,1.305686,1.974790,2.130657
25975,61871,1.295881,0.534912,0.206148,-0.039106,0.174602,0.799763,0.599267,0.553634,0.424376,0.481623,0.478603,-0.267017,0.310983,-1.821499,0.301870,-0.218814,-0.150724,-0.391440

In [76]:
X_test_trans = pd.concat([cat_df_trans,cato_df_trans,num_df_trans],axis=1)

In [77]:
X_test_trans

,index,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel,index,Class,index,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,103044,0.0,1.0,1.0,0.0,0.0,1.0,103044,1.0,103044,...,0.424376,0.481623,0.478603,-0.267017,-1.384983,-0.241216,-1.399262,0.543436,-0.386892,-0.391440
1,43282,1.0,0.0,1.0,0.0,1.0,0.0,43282,0.0,43282,...,-1.849662,0.481623,0.478603,0.493055,0.310983,-1.031357,0.301870,0.543436,-0.308169,-0.391440
2,65543,1.0,0.0,1.0,0.0,1.0,0.0,65543,1.0,65543,...,-1.091649,-1.017398,-1.850069,-1.027090,0.310983,-1.821499,0.301870,-0.981064,-0.386892,-0.391440
3,65083,1.0,0.0,1.0,0.0,0.0,1.0,65083,1.0,65083,...,-1.849662,-1.766908,-0.297621,1.253128,0.310983,1.339067,0.301870,-1.743314,-0.386892,-0.391440
4,76496,0.0,1.0,1.0,0.0,1.0,0.0,76496,0.0,76496,...,0.424376,0.481623,0.478603,-1.787163,1.158966,1.339067,-2.249827,0.543436,-0.386892,-0.391440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,121239,1.0,0.0,1.0,0.0,0.0,1.0,121239,1.0,121239,...,-1.091649,0.481623,0.478603,0.493055,0.310983,-0.241216,0.301870,0.543436,-0.386892,-0.391440
25972,6010,1.0,0.0,1.0,0.0,1.0,0.0,6010,0.0,6010,...,1.182388,1.231133,1.254828,1.253128,1.158966,1.339067,1.152435,-0.218814,-0.281928,-0.391440
25973,101127,0.0,1.0,1.0,0.0,1.0,0.0,101127,2.0,101127,...,0.424376,0.481623,-0.297621,-1.027090,1.158966,-0.241216,0.301870,0.543436,-0.334410,-0.391440
25974,82323,0.0,1.0,1.0,0.0,1.0,0.0,82323,0.0,82323,...,1.182388,1.231133,0.478603,0.493055,0.310983,1.339067,0.301870,1.305686,1.974790,2.130657
25975,61871,1.0,0.0,1.0,0.0,0.0,1.0,61871,1.0,61871,...,0.424376,0.481623,0.478603,-0.267017,0.310983,-1.821499,0.301870,-0.218814,-0.150724,-0.391440

In [78]:
X_test_trans.pop('index')

        index   index   index
0      103044  103044  103044
1       43282   43282   43282
2       65543   65543   65543
3       65083   65083   65083
4       76496   76496   76496
...       ...     ...     ...
25971  121239  121239  121239
25972    6010    6010    6010
25973  101127  101127  101127
25974   82323   82323   82323
25975   61871   61871   61871

[25976 rows x 3 columns]

In [79]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(X_train_trans,y_train_trans)

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [80]:
import pandas as pd

y_pred = model.predict(X_test_trans)

y_pred = pd.DataFrame(
    y_pred,
    columns=['Prediction']
)

y_pred

       Prediction
0               0
1               1
2               0
3               0
4               1
...           ...
25971           0
25972           1
25973           1
25974           1
25975           0

[25976 rows x 1 columns]

In [81]:
y_test_trans = LE.transform(y_test)

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [82]:
y_test_trans

array([0, 1, 0, ..., 1, 1, 0], shape=(25976,))

In [83]:
import pandas as pd

y_test_trans = LE.transform(y_test)

y_test_trans = pd.DataFrame(y_test_trans, columns=['target_encoded'])

y_test_trans

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

       target_encoded
0                   0
1                   1
2                   0
3                   0
4                   1
...               ...
25971               0
25972               1
25973               1
25974               1
25975               0

[25976 rows x 1 columns]

In [84]:
## How to save your production file
import joblib

joblib.dump({'model':model,'cat_encod':OHE,'cato_encod':OE,'output_encod':LE,'num_encod':STD},'model_prod1323_file.pkl')

['model_prod1323_file.pkl']

In [86]:
from sklearn.metrics import classification_report

print(classification_report(y_test_trans, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.96      0.94     14622
           1       0.95      0.89      0.92     11354

    accuracy                           0.93     25976
   macro avg       0.93      0.92      0.93     25976
weighted avg       0.93      0.93      0.93     25976